### ISSUE TITLE
Make mini gallery appear under each function documentation on website

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-nirs#113]
In the API section of the website, when the page for each function is open I would like it to have a list of examples that use the function.

I looked here but couldn't get it working... https://sphinx-gallery.github.io/stable/configuration.html#add-mini-galleries-for-api-documentation

**Comment by agramfort** [comment]
copy this files from mne python

_templates/class.rst
_templates/function.rst

maybe this will work. If not @larsoner may spot the issue quickly

>

**Comment by rob-luke** [comment]
Thanks @agramfort. I have opened #114 to build this in the ci and incase it helps highlight where my issue is.
