### ISSUE TITLE
Make glm contrast plot titles match MNE

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-nirs#122]
Currently the topographic contrast plots have the labels `hbo` and `hbr`, whereas the MNE plots show `Oxyhaemoglobin` and `Deoxyhaemoglobin`. We should change our plots to match MNE.

Example of MNE-NIRS incorrect labelling: https://mne.tools/mne-nirs/auto_examples/plot_10_hrf.html#compute-contrasts

Example of MNE correct labelling: https://mne.tools/stable/auto_tutorials/preprocessing/plot_70_fnirs_processing.html#view-consistency-of-responses-across-trials

**Comment by mshader** [comment]
Function lives here

https://github.com/mne-tools/mne-nirs/blob/master/mne_nirs/visualisation/_plot_GLM_topo.py#L101
