### ISSUE TITLE
Simplify requirements and environment.yml

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-nirs#160]
As discussed in #159 

> you might also consider trimming environment.yml and requirements.txt to just what's needed for MNE-NIRS.

**Comment by rob-luke** [comment]
Can I make the tests run weekly so that we catch upstream bugs earlier, rather than noticing when someone opens a PR?

**Comment by larsoner** [comment]
Yes, most CIs provide a way to run on a weekly/daily/whatever schedule in addition to being triggered by PRs

**Comment by rob-luke** [comment]
Thanks I'll check this out. Excuse the notes to myself here, it helps me not loose track of issues.
