### ISSUE TITLE
Improve formatting of stats models tables in sphinx gallery output

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-nirs#176]
See https://github.com/mne-tools/mne-nirs/pull/167#issuecomment-698281368

**Comment by larsoner** [comment]
If you are lost as to what I'm talking about or don't want to take the time to deal with the CSS, etc. let me know. I've worked a lot between MNE-Python / Sphinx-gallery / Python / CSS on this stuff so I can help if need be. But I am not an expert by any means so if you (or some other contributor) know what they're doing I'm happy to review a CircleCI output or some code along the way.

**Comment by rob-luke** [comment]
Thanks for the offer. I am hesitant to use your time up on aesthetic issues, I really appreciate your input and feel I should only ask your assistance once I have taken a good stab at it. I spent a bit of time yesterday trying to understand. But I didn't manage to wrap my head around CSS and Sphinx, so I decide to merge and fix separately. I would like this fixed this at some stage, but a higher priority for me is to get the MNE-NIRS test coverage up and clean up the API. If this is a one liner for you then please go ahead, but if its going to take some investigation then I am happy to investigate in the future.

**Comment by rob-luke** [comment]
Closed in #180
