### ISSUE TITLE
Move unit tests to GitHub actions

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-nirs#197]
Travis Mac job keeps failing. Move to GitHub actions. See the MNE transition at https://github.com/mne-tools/mne-python/pull/8161

**Comment by larsoner** [comment]
Travis is going to start allowing only 1000 minutes per month for open-source projects. I recommend waiting for https://github.com/mne-tools/mne-python/pull/8514 to land then just move all Travis jobs the same way

**Comment by rob-luke** [comment]
Looks like its landed, ill take a read. Thanks
