### ISSUE TITLE
Release package on pip

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-nirs#198]
Now that the two upstream packages have released nirs compatible versions (MNE and nilearn) it would be good to be able to run 'pip install mne-nirs'.

@agramfort and @larsoner, as this package is within the MNE organisation do I need to do anything specific to release this (do I need an owner to help)? Or can I just follow general tutorials online?

**Comment by agramfort** [comment]
try and if you need help ask. But I think you should be good

**Comment by rob-luke** [comment]
Thanks @agramfort  it seems to have worked. https://pypi.org/project/mne-nirs/
