### ISSUE TITLE
Build docs for multiple versions including dev

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-nirs#202]
I would like to have the docs available for each released version and for the latest dev branch, the same as MNE.

**Comment by rob-luke** [comment]
Maybe look at https://sphinx-versions.readthedocs.io/en/latest/index.html

**Comment by rob-luke** [comment]
Once this is done then change version to `0.0.2 dev`

**Comment by rob-luke** [comment]
Seems sphinx-versions doesn't work with this theme. Need to find another solution

**Comment by larsoner** [comment]
@rob-luke I would try transitioning completely to pydata-sphinx-theme + sphinx-multiversions See https://github.com/mne-tools/mne-python/issues/8184

**Comment by rob-luke** [comment]
Thanks @larsoner that's exactly what I was after.

**Comment by rob-luke** [comment]
This generally works now, so will close. A list of improvements is listed in #220
