### ISSUE TITLE
Replace CircleCI with GitHub Actions

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-nirs#206]
Currently I build all docs with GitHub Actions. And the webpage is created using GH actions.

However, to easily view docs in PRs I use circleci as you can browse the temporary docs using a web browser. (you can view the GH actions artefact, but requires downloading a zip and extracting).

Once you can view GitHub Actions artefacts in browser I will switch to this.

See https://github.com/actions/upload-artifact/issues/14

**Comment by larsoner** [comment]
There is a project @agramfort knows about (I can't remember the name) that builds docs with GH Actions, then uses CircleCI just to download and expose them as artifacts IIRC. @agramfort which one was it?

**Comment by rob-luke** [comment]
I believe this is it https://github.com/braindecode/braindecode/blob/master/.circleci/config.yml

**Comment by larsoner** [comment]
Closing as wontfix :)
