### ISSUE TITLE
BUG: statsmodels_to_results suffers from inaccuracy

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-nirs#244]
Using `.summary()` is nice for printing but bad for numerical computing, so we probably shouldn't use it to get actual values in `statsmodels_to_results`. By way of example:
```
>>> ch_model = smf.mixedlm(
...     "theta ~ -1 + ch_name:Condition",
...     ch_summary, groups=ch_summary["subject"]).fit(method='powell')
>>> ch_model_df = mne_nirs.statistics.statsmodels_to_results(ch_model)
>>> print(np.array(ch_model_df['P>|z|'])[17:33])
[0.    0.135 0.541 0.89  0.146 0.033 0.221 0.19  0.191 0.002 0.112 0.018
 0.129 0.    0.952 0.   ]
>>> print(np.array(ch_model.pvalues)[17:33])
[2.07866441e-07 1.35295118e-01 5.40928010e-01 8.90354390e-01
 1.46297283e-01 3.25360602e-02 2.20535361e-01 1.90387112e-01
 1.91051924e-01 2.39444468e-03 1.11936842e-01 1.77914955e-02
 1.29375584e-01 1.17267783e-04 9.52492330e-01 5.13254033e-05]
```
I think in the current code, any p-value less than `0.0005` significance will becomes `0.0` due to imprecision.

**Comment by rob-luke** [comment]
Great catch. I can look at this next week. Or do you want to submit a fix?

I'm loving that you're using this and finding issues. This api is version 1, but I have plans/ideas for improvements to work on this year. So please feel free to raise issues for any small frustrations too.

**Comment by rob-luke** [comment]
But as you've said to me before. First make it correct, so I want to squish as many accuracy bugs as possible and get robust tests before changing api.

**Comment by larsoner** [comment]
> Or do you want to submit a fix?

There are several numerical values, probably all of them need to be replaced. Not sure what the best way to do this is -- currently the `.summary()` table is used, I guess a mapping between the columns of that table that need to be replaced and their replacement attributes like `{'P>|z|': 'pvalues', 'P>|t|': 'pvalues', ...}` would work. I can make a PR for this next week but feel free to tackle it before then (this way or some other way) if you want
