### ISSUE TITLE
Snirf reader can't handle stim with only 1 entry in the data stream

### ISSUE THREAD

**Issue by kdarti** [mne-tools/mne-nirs#257]
If a "stimulus measurement data stream", i.e. /nirs{i}/stim{i}/data contains a single entry, then read_raw_snirf runs into an issue with indexing on line 269: https://github.com/mne-tools/mne-python/blob/93359566261be5c3fe7ceef8cb1fefce910cca52/mne/io/snirf/_snirf.py#L269

This could be fixed by e.g. forcing a 2d array:

data = np.atleast_2d(np.array(dat.get('/nirs/' + key + '/data')))

**Comment by rob-luke** [comment]
Thanks for raising this issue. I will address this tomorrow. And will @ you when I've been able to reproduce the error.

Thanks!

**Comment by larsoner** [comment]
Fixed by mne-tools/mne-python#9347 (I think)

**Comment by rob-luke** [comment]
I will double check today by recording a file with a single trigger. But we did implement the change suggest led by @kdarti, so I guess it's fixed.

Thanks @kdarti for raising the issue and for making life easy by suggesting the solution!
