### ISSUE TITLE
Dataset downloading is broken until MNE-python is fixed

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-nirs#386]
#### Describe the bug
Apparently this package won't load and complains about dataset downloaded not working. 

#### Steps to reproduce
Haven't reproduced myself but I expect it's due to recent changes in how MNE downloads datasets. It's been changed to use poooch by @adam2392

#### Additional information

I will wait for https://github.com/mne-tools/mne-python/pull/9763 before I can fix this

**Comment by drammock** [comment]
@rob-luke can you say more about what's broken?  What did you try to do and what happened?

**Comment by rob-luke** [comment]
I haven't tried myself yet. But I just received an email from a user reporting the above. And it makes sense given I use internal MNE functions and that's been modified recently.

Here's the report I got...

file:///var/mobile/Library/SMS/Attachments/ec/12/483F6F29-315D-4DD5-BD56-B03A675FF6F9/Screen%20Shot%202021-09-20%20at%205.23.10%20pm.jpeg

Kicking off a CI should confirm if this issue exists

**Comment by drammock** [comment]
ah, OK. yeah, `_download()` was removed yesterday.  Lemme see if I can quickly bang out a fix for you (I have 30 minutes before I go on leave for a week :)

**Comment by rob-luke** [comment]
That would be very kind of you!

**Comment by adam2392** [comment]
I'm going to finish off https://github.com/mne-tools/mne-python/pull/9763 tonight, which should allow you to refactor your fetching code to follow that framework.

**Comment by rob-luke** [comment]
Thanks @adam2392 and @drammock for keeping me posted. The new functionality is very cool and I look forward to using it. Once its up and running I have a few more open datasets to add.

**Comment by rob-luke** [comment]
Cross referencing #388
