### ISSUE TITLE
ENH: Montage plots for fNIRS

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-nirs#440]
Not sure if this should go in MNE-Python, MNE-NIRS, or neither (?), but I've repeatedly wanted to show (in papers, and just to make sure I'm doing things correctly) plots of fNIRS electrodes labeled with the 10-20 coordinates they have when they are being positioned on the subject. However:

1. fNIRS channels have specific namings related to their source-detector pairings and wavelengths, so `rename_channels` is not a good option
2. The channels we actually record are a combination of a source-detector pair, like the yellow dots [here](https://mne.tools/dev/auto_tutorials/preprocessing/70_fnirs_processing.html#viewing-location-of-sensors-over-brain-surface):

    ![](https://mne.tools/dev/_images/sphx_glr_70_fnirs_processing_001.png)

3. However, the optodes that are placed on the heads are actually sources and detectors, i.e., the red and dark red/brown above.

What I've found really useful for sanity checking is a multi-view plot with ideal 10-20 locations, plus the resulting fNIRS channel numbers (starting from 1; here for a Hitachi system):

![montage](https://user-images.githubusercontent.com/2365790/152046225-4c25c480-d256-4796-ac3c-43baada12038.png)

For MNE-Python, it might be useful to add text labels to channels in `plot_alignment`, though I'm not sure how nicely these could be made to interact with 3D view manipulations. (My code currently uses the given 3D-to-2D projection to add 2D text actors. Proper 3D interaction would be tougher, since we'd need to place the text in the 3D scene -- probably with some offset "outward" so that it doesn't overlap with the channel sphere -- and make sure it draws nicely with translucent geometry and such).

So I think overall I'm inclined to just implement some sort of `mne_nirs.viz.plot_3d_montage` or something. If folks agree about that scope, then I'll transfer this issue over to the MNE-NIRS repo and hash out an API with @rob-luke.

**Comment by rob-luke** [comment]
I would absolutely use this. Currently I am exporting the existing figure and adding labels in photoshop.

How are the channel numbers defined and do they correspond to anything in the info structure? Could we have an option to enable and disable the source/detector labels and channel labels independently? Sometimes I just want channel labels, and sometimes I just want the S/D labels.

**Comment by larsoner** [comment]
> Currently I am exporting the existing figure and adding labels in photoshop.

:scream: 

> How are the channel numbers defined and do they correspond to anything in the info structure? Could we have an option to enable and disable the source/detector labels and channel labels independently? Sometimes I just want channel labels, and sometimes I just want the S/D labels.

They are just the 1-based indices of every other channel (i.e., every pair) in `raw_intensity`. So maybe to start a first API could be like:
```
plot_3d_montage(info, *, view_map, subject='fsaverage', trans='fsaverage', src_names=None, det_names=None, ch_names=None, subjects_dir=None)
```
where:

- `src/det_names` can be a dict to map `S1...SN` and `D1...DN` to human-readable names (typically from a 10-20)
- `ch_names` can be `None` to use the native names (`S1_D1 760` or whatever), or `'numeric'` to use 1-N as the names (as I've done here)
- `view_map` is the tricky part -- I think this would be a dict of view->ch index mappings saying which channel indices will be shown in each view. For this dataset for example it would be `view_map={'left-lat': np.arange(0, 24, 2), 'right-lat': np.arange(24, 48, 2)}` or something. Or maybe better, we recognize the paired nature of the data and do `view_map={'left-lat': np.arange(0, 12), 'right-lat': np.arange(12, 24)}` which means "first 12 pairs in a left lateral view, next 12 pairs in right lat".
 
I think that would cover my use case at least.

**Comment by rob-luke** [comment]
> 😱

I know! Please don't tell anyone.

> src_det_names can be a dict to map S1...SN and D1...DN to human-readable names (typically from a 10-20)

I have an attempt at guessing the closest 10-20 position given a coordinate at:

https://github.com/mne-tools/mne-nirs/blob/177b61e8dbaecd9e627d0b794e0684fc674f2f0e/mne_nirs/io/fold/_fold.py#L72

Could we use something (probably a smarter version) like this if `src_det_names = None`? Or is this just going to overcomplicate things?

> view_map is the tricky part 

Yeah seems tricky, but your suggestion makes sense.

**Comment by larsoner** [comment]
I would make that 'auto', and we can try it as the default. We could even check if the estimated locations are "close enough" to standard 10-20 ones, and only use those if they are. If most fNIRS people use 10-20 on fsaverage then it's a good choice. Then None can just label as S1, D1, etc.
