### ISSUE TITLE
MAINT: Release?

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-nirs#447]
MNE-Python is planning to release 1.0 in the next few days. @rob-luke can I push out a new MNE-NIRS at the same time?

If so, do you have a process documented somewhere that I should follow? If not, my plan unless you suggest otherwise would be to

1. Change the version `'0.1.3 dev'` to `0.2.0`, commit, push
2. Make release on GitHub (tagged as v0.2.0)
3. `python setup.py bdist_wheel sdist` then upload to PyPi using a `__token__`
4. Push as `upstream/maint/0.2`
5. Change the version to `'0.3.dev0'`  (note slightly different from above, since I think it's more PEP440 / standard across scientific python to name like this), commit, push

Somewhere between (4) and (5) I'd usually make sure doc builds work. But since doc building is currently a bit broken / needs to be refactored (?), doing (4) allows us to take this at our own speed -- we can make CircleCI build + upload for `maint/0.2` just like we do for MNE-Python, and it should push the stable docs, etc. Basically we can delay our docs update for a few days while we sort out CIs.

If this sounds good to you and you want me to proceed, I think all I should need is PyPi maintainer access to mne-nirs. My username there is Eric89GXL. However, since you're the sole owner, I'd recommend actually making me an owner, as well, so that there is more than one.

**Comment by rob-luke** [comment]
The current release process is described at https://github.com/mne-tools/mne-nirs/blob/main/doc/release.md

I am happy for you to optimise the process wherever you see fit. Please also update the release procedure as well so that I can learn and replicate it in the future.

I'll add your username, good idea.

I am happy to make the new release whenever you want. Or you can. Whatever you prefer.

**Comment by larsoner** [comment]
I updated https://github.com/mne-tools/mne-nirs/blob/main/doc/release.md to :+1: 

1. `python setup.py sdist bdist_wheel` (added `bdist_wheel`) so that a wheel is built and uploaded as well
2. Add a `git push upstream main:maint/0.X`

That second one will help with individualized doc builds, I think. Otherwise those look reasonable to me.

**Comment by rob-luke** [comment]
Thanks

**Comment by rob-luke** [comment]
>  I think all I should need is PyPi maintainer access to mne-nirs

Gave you full owner access. Let me know if there was any issues with the invite

**Comment by larsoner** [comment]
@rob-luke okay to move `release.md` to a Wiki? I was making a bunch of edits then I realized that, by doing so, I was triggering the CIs to run over and over again...

If you want to keep it as part of the repo I can also work on remembering to `[ci skip]` when making changes instead

**Comment by larsoner** [comment]
Release done! Now the docs are dev-only, but that's tracked in #449

**Comment by rob-luke** [comment]
Thanks @larsoner !! I am looking forward to trying this with the new installers.
