### ISSUE TITLE
MAINT: Testing policy

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-nirs#448]
For maintainability, it's usually good to maintain compatibility with at least the current stable version of MNE-Python. @rob-luke okay to adopt this policy, and formalize it via CIs testing against MNE-Python `main` as well as the latest `pip`/`conda`-installable version?

**Comment by rob-luke** [comment]
Absolutely @larsoner, I'd greatly appreciate that.

I try to watch the MNE-Python CI files and mirror any changes back to MNE-NIRS, but I often fall behind and try and align them again before each release.

In short, edit away 😃
