### ISSUE TITLE
Follow MNE-Python and remove pyqt5 and move to pyside6

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-nirs#471]
To minimise maintenance and ensure compatability, it is best to follow the practices and packages from MNE-Python. So let's move to pyside6 https://github.com/mne-tools/mne-python/pull/10513

**Comment by rob-luke** [comment]
Before starting on this. Please check if MNE-Python is still using PySide6, or have they moved to PySide32 by now? Use whatever is being used in MNE-Python

**Comment by larsoner** [comment]
PyQt6 for pip, still PyQt5 for conda. PySide6 does not work well for REPL interpreter matplotlib interactive mode.

**Comment by rob-luke** [comment]
Simple 😉
But seriously, thanks for the explanation, greatly appreciated!
