### ISSUE TITLE
Update docs, CI, etc for new organisation

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-nirs#50]
This repository has been transferred from my account to mne-tools. All the links need to be regenerated. The gh-pages needs to be set up, etc.

- [x] Travis
- [x] Fix README links and badges
- [x] Deploy to GitHub pages
- [x] Run linter on PRs
- [x] Test docs build on PRs
- [x] Fix link at top of repo landing page
- [ ] Appveyor

**Comment by rob-luke** [comment]
@agramfort I am unable to change the link at the top of the repository landing page. It should point to `https://mne.tools/mne-nirs/`. Can you please change it.

**Comment by rob-luke** [comment]
Everything except AppVeyor seems to be working now.

I can manually trigger AppVeyor builds on their website, but they do not build automatically. Also the badge link takes me to an error. Maybe it needs someone with admin access to activate this service.

**Comment by agramfort** [comment]
URL fixed

regarding appveyor not sure. Maybe time to switch to azure pipelines?

project template should be updated too :(

>

**Comment by rob-luke** [comment]
Thanks @agramfort 

I have removed appveyor. I will open an issue to add azure testing.

The template was a great help. After some playing round I opted for GitHub Actions for basic pep8 testing instead of pep8speaks, and for building the sphinx website. But happy to switch to another approach if preferred.

**Comment by agramfort** [comment]
the template was done before GitHub Actions

we should update the template  now.

can you give a hand or just tell us what you adapted so we can
backport to template project?

**Comment by rob-luke** [comment]
Easy, I'll open some pull requests tomorrow.
