### ISSUE TITLE
vlim boundaries not working properly for plot_glm_group_topo

### ISSUE THREAD

**Issue by HanBnrd** [mne-tools/mne-nirs#522]
#### Describe the bug
When `None` is used as one of the boundaries for vlim in [plot_glm_group_topo](https://mne.tools/mne-nirs/dev/generated/mne_nirs.visualisation.plot_glm_group_topo.html), it is not actually taking the min/max of the data.

#### Steps to reproduce
According to [those lines of code](https://github.com/mne-tools/mne-nirs/blob/c7cf3465b1a1729b21f795ba1857652e0eee4805/mne_nirs/visualisation/_plot_GLM_topo.py#L318-L322), here are, I think, some problematic cases:
- if `vlim = (None, whatever)`, we will have vmin set to `-whatever` and not the minimum data value 
- if `vlim = (negative_value, None)`, with only negative data values, we will have vmax set to a positive value and not the actual max value of the data

#### Expected results
The function actually uses the min or max of the data for the vlim boundary set to `None`.

#### Suggested fix
Replacing [this](https://github.com/mne-tools/mne-nirs/blob/c7cf3465b1a1729b21f795ba1857652e0eee4805/mne_nirs/visualisation/_plot_GLM_topo.py#L318-L322) by this:
```python
    vmin, vmax = vlim
if vmax is None:
    vmax = np.max(estimates)
if vmin is None:
    vmin = np.min(estimates)
```

**Comment by larsoner** [comment]
Can you check the default `cmap`? If it's `RdBu_r` for example the idea is that the white midpoint should stay at zero. So if you set the max the min should be `-max`, and if you set the min the max should be `-min`.

I think ideally we would maintain compatibility with however we handle this stuff in MNE-Python topomap plotting. It could be the above behavior but that needs to be checked...

**Comment by HanBnrd** [comment]
Yes I should have specified, the default is `RdBu_r` indeed, however I was think about it more in the the case where we would use `mpl.cm.Oranges` and `mpl.cm.Blues_r` as in [this example](https://mne.tools/mne-nirs/stable/auto_examples/general/plot_12_group_glm.html#group-topographic-visualisation):
```python
# Plot the two conditions
plot_glm_group_topo(raw_haemo.copy().pick(picks="hbo"),
                    ch_model_df.query("Condition in ['Tapping_Left']"),
                    colorbar=False, axes=axes[0, 0],
                    vlim=(0, 20), cmap=mpl.cm.Oranges)

plot_glm_group_topo(raw_haemo.copy().pick(picks="hbo"),
                    ch_model_df.query("Condition in ['Tapping_Right']"),
                    colorbar=True, axes=axes[0, 1],
                    vlim=(0, 20), cmap=mpl.cm.Oranges)


# Plot the two conditions
plot_glm_group_topo(raw_haemo.copy().pick(picks="hbr"),
                    ch_model_df.query("Condition in ['Tapping_Left']"),
                    colorbar=False, axes=axes[1, 0],
                    vlim=(-10, 0), cmap=mpl.cm.Blues_r)
plot_glm_group_topo(raw_haemo.copy().pick(picks="hbr"),
                    ch_model_df.query("Condition in ['Tapping_Right']"),
                    colorbar=True, axes=axes[1, 1],
                    vlim=(-10, 0), cmap=mpl.cm.Blues_r)
```

I feel that it would make sense to possibly use for HbO data `vlim=(0, None)` where we would expect the vmax to be the highest positive value, and for HbR data `vlim=(None, 0)` where we would expect the vmin to be the lowest negative value.

But I understand how the current implementation makes sense in the `RdBu_r` case. However I feel like it's more common to use shades of red/orange for HbO (the more positive the darker) and shades of blue for HbR (the more negative the darker).

**Comment by larsoner** [comment]
Maybe to support both use cases instead of changing what `None` means or how it behaves we could add a new behavior -- make it so you could do `("min", 0)` and `(0, "max")`

**Comment by HanBnrd** [comment]
Actually, thinking more about it, and after checking NIRS-toolbox, I feel like `RdBu_r` is probably the best way to use this function.
> ![image](https://github.com/mne-tools/mne-nirs/assets/32393169/eb90b33d-514c-49c6-a28b-dfbbbb5fb916)
> *(NIRS-toolbox topo)*

Forcing colours for HbO and HbR could look misleading... Maybe the tutorial shouldn't even show how to do that? Though it's good to showcase capabilities.

**Comment by larsoner** [comment]
Either way is fine with me... maybe a `.. note::` somewhere about how to be careful with `vlim` would make sense

**Comment by HanBnrd** [comment]
Closing because the behaviour makes sense
