### ISSUE TITLE
Set up CircleCI to build docs

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-nirs#60]
The current GitHub doc building service has the following shortcoming:
* Can not preview docs for PRs. It builds them, but you only see a pass or fail.
* ~~Ram is limited to 8 GB which is too small for the HRF demo~~ I think ill improve code efficiency instead

MNE uses CircleCI. I would like to be as similar/compliant with MNE as possible.

See https://github.com/mne-tools/mne-python/blob/master/.circleci/config.yml

**Comment by rob-luke** [comment]
@larsoner @agramfort I logged on to circle ci but can not enable mne-nirs as I don't have permission. Could someone please enable circleci for this repo so that I can preview doc builds in PR in the same fashion as MNE.

Thanks

**Comment by agramfort** [comment]
done

**Comment by rob-luke** [comment]
Thanks @agramfort 

Closed in #78
