### ISSUE TITLE
Create artificial data / simulate datasets

### ISSUE THREAD

**Issue by rob-luke** [mne-tools/mne-nirs#66]
Add functionality to simulate NIRS data. This will be useful for testing, documentation, and algorithm verification.

**Comment by larsoner** [comment]
At least in principle if you had a method of computing a forward solution (mapping from unit Am dipole current in the brain to NIRS sensor readings), you'd get this (and source localization, sensitivity maps, etc.) for free. But I don't know how reasonable that is, so do what you need to do :)

**Comment by rob-luke** [comment]
Thanks, I had not considered a forward solution. I do recall reading one paper on forward solutions for NIRS, will see if I can dig it up again.
